### ISSUE TITLE
No new updates on Hackage?

### ISSUE THREAD

**Issue by qrilka** [singpolyma/currency-haskell#5]
I have noticed bug with the code on Hackage but I see it fixed in the repo - any plans to release a new version?

**Comment by singpolyma** [comment]
A bug with the code or the metadata?  I should be able to update the metadata on hackage without having to upload a new version number, but it's not letting me right now...

**Comment by qrilka** [comment]
Probably it was too late in that day and now it looks like the code is OK. For some reason I thought there was only `RUR` in `toEnum` and `RUB` in `fromEnum`. But after another look it seems that I just missed some lines somehow.
